#!/bin/bash

# Function to display usage instructions
usage() {
    echo "Usage: $0 [-m message] [-r recipient]"
    exit 1
}

#cool

# Parse command-line options
while getopts ":m:r:" opt; do
    case ${opt} in
        m )
            message=$OPTARG
            ;;
        r )
            recipient=$OPTARG
            ;;
        \? )
            usage
            ;;
    esac
done

# Check if required options are provided
if [ -z "$message" ] || [ -z "$recipient" ]; then
    usage
fi

# Simulate sending a message to a recipient
echo "Sending message: '$message' to recipient: '$recipient'"
