#ifndef ALL_ERRORS_HPP
#define ALL_ERRORS_HPP

#define SUCCESS 0
#define ERR_INVALID_ARGS 1
#define ERR_USERNAME_TOO_LONG 2
#define ERR_INVALID_CHARACTER 3
#define ERR_SIGNAL_HANDLING 4
#define ERR_PIPE_CREATION 5
#define ERR_PROCESS_CREATION 6
#define ERR_NO_EXISTING_FILE 7
#define ERR_PIPE_WRITE_READ_OPENING 8
#define ERR_SHARED_MEMORY 9
#endif 