#ifndef ALL_ERRORS_HPP
#define ALL_ERRORS_HPP

#define SUCCESS 0
#define ERR_INVALID_ARGS 1
#define ERR_USERNAME_TOO_LONG 2
#define ERR_INVALID_CHARACTER 3
#define ERR_SIGNAL_HANDLING 4
#define ERR_PROCESS_CREATION 5
#define ERR_PIPE_RELATED 6
#define ERR_SHARED_MEMORY 7

#endif 